language: rust
env:
  global:
    - secure: "LTcT7C715JhhozqmTGqsdiKeF/o+KN9sBtLd2HuyxsaKPeG1Ays+lMi2Xy6V1vttzOlnyMu+y9oLyI2mJI6I9cdAc4WdYGyrnJHJWpOP9YmPuFcCaDqDEOc/D9wf18iwrBw7+/FZswYgYUAieYcSoDclF4RpWDK0TCzmMqvo//s="
install: sudo apt-get install libao-dev
script:
  - cargo test
after_script:
  - rustdoc -L target/test -L target/test/deps src/lib.rs
  - curl -O https://bitbucket.org/tari/tari.bitbucket.org/raw/default/travis_push.sh && sh travis_push.sh doc audiostream.rs
